// import "./globals.css";

// import "@fontsource/roboto/300.css";
// import "@fontsource/roboto/400.css";
// import "@fontsource/roboto/500.css";
// import "@fontsource/roboto/700.css";

import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { Providers } from "@/redux/provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className} style={{ margin: 0, padding: 0 }}>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
